// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvEE0X6tXidcL5Op6GKlMmSydmhHUD6Gw',
    appId: '1:539607174558:web:d1b20b91b5ef0c0bd6da8f',
    messagingSenderId: '539607174558',
    projectId: 'crypto-list-app-4fccb',
    authDomain: 'crypto-list-app-4fccb.firebaseapp.com',
    storageBucket: 'crypto-list-app-4fccb.appspot.com',
    measurementId: 'G-GMH3QHTNE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuuwhevGPgNwGGDycgI3ME-K2WestwN0',
    appId: '1:539607174558:android:b468d770a32618a8d6da8f',
    messagingSenderId: '539607174558',
    projectId: 'crypto-list-app-4fccb',
    storageBucket: 'crypto-list-app-4fccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoKCWy9mYDUPL9jJ4JSZzSDrThkByFlQk',
    appId: '1:539607174558:ios:e38111960df0cd70d6da8f',
    messagingSenderId: '539607174558',
    projectId: 'crypto-list-app-4fccb',
    storageBucket: 'crypto-list-app-4fccb.appspot.com',
    iosClientId: '539607174558-ohs3fmom7huhslq0te6fflepej38rvm6.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoKCWy9mYDUPL9jJ4JSZzSDrThkByFlQk',
    appId: '1:539607174558:ios:e38111960df0cd70d6da8f',
    messagingSenderId: '539607174558',
    projectId: 'crypto-list-app-4fccb',
    storageBucket: 'crypto-list-app-4fccb.appspot.com',
    iosClientId: '539607174558-ohs3fmom7huhslq0te6fflepej38rvm6.apps.googleusercontent.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );
}
